#ifndef __INFO__
#define __INFO__

#include "d_think.h"

typedef enum {
    SPR_TROO, SPR_SHTG, SPR_PUNG, SPR_PISG, SPR_PISF,
    SPR_SHTF, SPR_SHT2, SPR_CHGG, SPR_CHGF, SPR_MISG,
    SPR_MISF, SPR_SAWG, SPR_PLSG, SPR_PLSF, SPR_BFGG,
    SPR_BFGF, SPR_BLUD, SPR_PUFF, SPR_BAL1, SPR_BAL2,
    SPR_PLSS, SPR_PLSE, SPR_MISL, SPR_BFS1, SPR_BFE1,
    SPR_BFE2, SPR_TFOG, SPR_IFOG, SPR_PLAY, SPR_POSS,
    SPR_SPOS, SPR_VILE, SPR_FIRE, SPR_FATB, SPR_FBXP,
    SPR_SKEL, SPR_MANF, SPR_FATT, SPR_CPOS, SPR_SARG,
    SPR_HEAD, SPR_BAL7, SPR_BOSS, SPR_BOS2, SPR_SKUL,
    SPR_SPID, SPR_BSPI, SPR_APLS, SPR_APBX, SPR_CYBR,
    SPR_PAIN, SPR_SSWV, SPR_KEEN, SPR_BBRN, SPR_BOSF,
    SPR_ARM1, SPR_ARM2, SPR_BAR1, SPR_BEXP, SPR_FCAN,
    SPR_BON1, SPR_BON2, SPR_BKEY, SPR_RKEY, SPR_YKEY,
    SPR_BSKU, SPR_RSKU, SPR_YSKU, SPR_STIM, SPR_MEDI,
    SPR_SOUL, SPR_PINV, SPR_PSTR, SPR_PINS, SPR_MEGA,
    SPR_SUIT, SPR_PMAP, SPR_PVIS, SPR_CLIP, SPR_AMMO,
    SPR_ROCK, SPR_BROK, SPR_CELL, SPR_CELP, SPR_SHEL,
    SPR_SBOX, SPR_BPAK, SPR_BFUG, SPR_MGUN, SPR_CSAW,
    SPR_LAUN, SPR_PLAS, SPR_SHOT, SPR_SGN2, SPR_COLU,
    SPR_SMT2, SPR_GOR1, SPR_POL2, SPR_POL5, SPR_POL4,
    SPR_POL3, SPR_POL1, SPR_POL6, SPR_GOR2, SPR_GOR3,
    SPR_GOR4, SPR_GOR5, SPR_SMIT, SPR_COL1, SPR_COL2,
    SPR_COL3, SPR_COL4, SPR_CAND, SPR_CBRA, SPR_COL6,
    SPR_TRE1, SPR_TRE2, SPR_ELEC, SPR_CEYE, SPR_FSKU,
    SPR_COL5, SPR_TBLU, SPR_TGRN, SPR_TRED, SPR_SMBT,
    SPR_SMGT, SPR_SMRT, SPR_HDB1, SPR_HDB2, SPR_HDB3,
    SPR_HDB4, SPR_HDB5, SPR_HDB6, SPR_POB1, SPR_POB2,
    SPR_BRS1, SPR_TLMP, SPR_TLP2,
    NUMSPRITES
} spritenum_t;

typedef enum {
    S_NULL,
    S_LIGHTDONE,
    S_PUNCH, S_PUNCHDOWN, S_PUNCHUP, S_PUNCH1, S_PUNCH2,
    S_PUNCH3, S_PUNCH4, S_PUNCH5,
    S_PISTOL, S_PISTOLDOWN, S_PISTOLUP, S_PISTOL1, S_PISTOL2,
    S_PISTOL3, S_PISTOL4, S_PISTOLFLASH,
    S_SGUN, S_SGUNDOWN, S_SGUNUP, S_SGUN1, S_SGUN2, S_SGUN3,
    S_SGUN4, S_SGUN5, S_SGUN6, S_SGUN7, S_SGUN8, S_SGUN9,
    S_SGUNFLASH1, S_SGUNFLASH2,
    S_DSGUN, S_DSGUNDOWN, S_DSGUNUP, S_DSGUN1, S_DSGUN2,
    S_DSGUN3, S_DSGUN4, S_DSGUN5, S_DSGUN6, S_DSGUN7,
    S_DSGUN8, S_DSGUN9, S_DSGUN10, S_DSNR1, S_DSNR2,
    S_DSGUNFLASH1, S_DSGUNFLASH2,
    S_CHAIN, S_CHAINDOWN, S_CHAINUP, S_CHAIN1, S_CHAIN2,
    S_CHAIN3, S_CHAINFLASH1, S_CHAINFLASH2,
    S_MISSILE, S_MISSILEDOWN, S_MISSILEUP, S_MISSILE1,
    S_MISSILE2, S_MISSILE3, S_MISSILEFLASH1, S_MISSILEFLASH2,
    S_MISSILEFLASH3, S_MISSILEFLASH4,
    S_SAW, S_SAWB, S_SAWDOWN, S_SAWUP, S_SAW1, S_SAW2,
    S_SAW3,
    S_PLASMA, S_PLASMADOWN, S_PLASMAUP, S_PLASMA1, S_PLASMA2,
    S_PLASMAFLASH1, S_PLASMAFLASH2,
    S_BFG, S_BFGDOWN, S_BFGUP, S_BFG1, S_BFG2, S_BFG3,
    S_BFG4, S_BFGFLASH1, S_BFGFLASH2,
    S_BLOOD1, S_BLOOD2, S_BLOOD3,
    S_PUFF1, S_PUFF2, S_PUFF3, S_PUFF4,
    S_TBALL1, S_TBALL2, S_TBALLX1, S_TBALLX2, S_TBALLX3,
    S_RBALL1, S_RBALL2, S_RBALLX1, S_RBALLX2, S_RBALLX3,
    S_PLASBALL, S_PLASBALL2, S_PLASEXP, S_PLASEXP2,
    S_PLASEXP3, S_PLASEXP4, S_PLASEXP5,
    S_ROCKET, S_BFGSHOT, S_BFGSHOT2,
    S_BFGLAND, S_BFGLAND2, S_BFGLAND3, S_BFGLAND4,
    S_BFGLAND5, S_BFGLAND6,
    S_BFGEXP, S_BFGEXP2, S_BFGEXP3, S_BFGEXP4,
    S_EXPLODE1, S_EXPLODE2, S_EXPLODE3,
    S_TFOG, S_TFOG01, S_TFOG02, S_TFOG2, S_TFOG3,
    S_TFOG4, S_TFOG5, S_TFOG6, S_TFOG7, S_TFOG8,
    S_TFOG9, S_TFOG10,
    S_IFOG, S_IFOG01, S_IFOG02, S_IFOG2, S_IFOG3,
    S_IFOG4, S_IFOG5,
    S_PLAY, S_PLAY_RUN1, S_PLAY_RUN2, S_PLAY_RUN3,
    S_PLAY_RUN4, S_PLAY_ATK1, S_PLAY_ATK2,
    S_PLAY_DIE1, S_PLAY_DIE2, S_PLAY_DIE3, S_PLAY_DIE4,
    S_PLAY_DIE5, S_PLAY_DIE6, S_PLAY_DIE7,
    S_PLAY_XDIE1, S_PLAY_XDIE2, S_PLAY_XDIE3, S_PLAY_XDIE4,
    S_PLAY_XDIE5, S_PLAY_XDIE6, S_PLAY_XDIE7, S_PLAY_XDIE8,
    S_PLAY_XDIE9,
    S_PLAY_PAIN, S_PLAY_PAIN2, S_PLAY_FDTH1,
    /* ... truncated for brevity, full table in info.c ... */
    NUMSTATES
} statenum_t;

typedef struct {
    spritenum_t sprite;
    int         frame;
    int         tics;
    actionf_t   action;
    statenum_t  nextstate;
    int         misc1;
    int         misc2;
} state_t;

typedef enum {
    MT_PLAYER, MT_POSSESSED, MT_SHOTGUY, MT_VILE,
    MT_FIRE, MT_UNDEAD, MT_TRACER, MT_SMOKE,
    MT_FATSO, MT_FATSHOT, MT_CHAINGUY, MT_TROOP,
    MT_SERGEANT, MT_SHADOWS, MT_HEAD, MT_BRUISER,
    MT_BRUISERSHOT, MT_KNIGHT, MT_SKULL, MT_SPIDER,
    MT_BABY, MT_CYBORG, MT_PAIN, MT_WOLFSS,
    MT_KEEN, MT_BOSSBRAIN, MT_BOSSSPIT, MT_BOSSTARGET,
    MT_SPAWNSHOT, MT_SPAWNFIRE, MT_BARREL,
    MT_TROOPSHOT, MT_HEADSHOT, MT_ROCKET, MT_PLASMA,
    MT_BFG, MT_ARACHPLAZ, MT_PUFF, MT_BLOOD,
    MT_TFOG, MT_IFOG, MT_TELEPORTMAN,
    MT_EXTRABFG, MT_MISC0, MT_MISC1, MT_MISC2,
    MT_MISC3, MT_MISC4, MT_MISC5, MT_MISC6,
    MT_MISC7, MT_MISC8, MT_MISC9, MT_MISC10,
    MT_MISC11, MT_MISC12, MT_INV, MT_MISC13,
    MT_INS, MT_MISC14, MT_MISC15, MT_MISC16,
    MT_MEGA, MT_CLIP, MT_MISC17, MT_MISC18,
    MT_MISC19, MT_MISC20, MT_MISC21, MT_MISC22,
    MT_MISC23, MT_MISC24, MT_MISC25, MT_CHAINGUN,
    MT_MISC26, MT_MISC27, MT_MISC28, MT_SHOTGUN,
    MT_SUPERSHOTGUN, MT_MISC29, MT_MISC30, MT_MISC31,
    MT_MISC32, MT_MISC33, MT_MISC34, MT_MISC35,
    MT_MISC36, MT_MISC37, MT_MISC38, MT_MISC39,
    MT_MISC40, MT_MISC41, MT_MISC42, MT_MISC43,
    MT_MISC44, MT_MISC45, MT_MISC46, MT_MISC47,
    MT_MISC48, MT_MISC49, MT_MISC50, MT_MISC51,
    MT_MISC52, MT_MISC53, MT_MISC54, MT_MISC55,
    MT_MISC56, MT_MISC57, MT_MISC58, MT_MISC59,
    MT_MISC60, MT_MISC61, MT_MISC62, MT_MISC63,
    MT_MISC64, MT_MISC65, MT_MISC66, MT_MISC67,
    MT_MISC68, MT_MISC69, MT_MISC70, MT_MISC71,
    MT_MISC72, MT_MISC73, MT_MISC74, MT_MISC75,
    MT_MISC76, MT_MISC77, MT_MISC78, MT_MISC79,
    MT_MISC80, MT_MISC81, MT_MISC82, MT_MISC83,
    MT_MISC84, MT_MISC85, MT_MISC86,
    NUMMOBJTYPES
} mobjtype_t;

typedef struct {
    int doomednum;
    int spawnstate;
    int spawnhealth;
    int seestate;
    int seesound;
    int reactiontime;
    int attacksound;
    int painstate;
    int painchance;
    int painsound;
    int meleestate;
    int missilestate;
    int deathstate;
    int xdeathstate;
    int deathsound;
    int speed;
    int radius;
    int height;
    int mass;
    int damage;
    int activesound;
    int flags;
    int raisestate;
} mobjinfo_t;

extern state_t    states[NUMSTATES];
extern mobjinfo_t mobjinfo[NUMMOBJTYPES];
extern char       *sprnames[NUMSPRITES + 1];

#endif
